version: '3.8'

services:
  # Spring Boot application service
  app:
    image: ubuntu:22.04
    container_name: springboot-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
      - maven-repo:/root/.m2
    working_dir: /app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    command: >
      bash -c "apt-get update && 
               apt-get install -y openjdk-17-jdk maven && 
               mvn spring-boot:run"

  # PostgreSQL database service
  db:
    image: ubuntu:22.04
    container_name: postgres-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    command: >
      bash -c "apt-get update && 
               apt-get install -y postgresql && 
               service postgresql start && 
               tail -f /dev/null"

volumes:
  maven-repo:
  postgres-data: