### GET request to example server
GET http://localhost:8080

### Get AIS
GET http://localhost:8080/ais_data

### Get AIS by ID
GET http://localhost:8080/ais_data/0

### POST AIS
POST http://localhost:8080/ais_data
Content-Type: application/json

{
    "mmsi":  "b",
    "latitude": 1,
    "longitude": 1,
    "speedOverGround": 1,
    "courseOverGround": 1,
    "timestamp": "2025-06-15T12:34:56"
}